### ISSUE TITLE
Need a different name for package

### ISSUE THREAD

**Issue by dsblank** [anntzer/matlab_kernel#1]
This repo should use a different name from matlab_kernel so that it doesn't conflict with the Calysto package.

**Comment by anntzer** [comment]
I don't think the two packages really overlap in usage, and as I argued in https://github.com/Calysto/matlab_kernel/pull/72 I think this package is closer to a vanilla MATLAB kernel anyway.

**Comment by anntzer** [comment]
@dsblank I came back on my decision.  This project (and kernel name) is now known as imatlab.

I allowed myself to take over that name in the ipython wiki list of kernels (https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages), given that the metakernel MATLAB Kernel doesn't refer to itself as "imatlab" anywhere at that point.

**Comment by dsblank** [comment]
Thanks!
